// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnzgcxxlkxkbiwisrlzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuemdjeHhsa3hrYml3aXNybHp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTc1OTksImV4cCI6MjA3MzA5MzU5OX0.0bIWFIJhiC9eCwqWKNQzYh3_9djYWl1OiyoeVzIgRK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});